version: "3.4"
# COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose up --build
services:
  api:
    image: api:dummy-arm32v7
    build:
      context: .
      dockerfile: ./Dockerfile.image.arm
