#### jar-dependency
jar-dependency:
  root-path: ${JAR_ROOT}
  signature-opt: ${SIGN_OPT}  #enable
#  container: testapi
#  docker-api-endpoint: http://192.168.3.239:2375

#### default
server:
  port: 8080

spring:
  # profiles:
  #   active: dev
  # view:
  #   prefix: /META-INF/view/
  #   suffix: .html
  mvc:
    static-path-pattern: /static/**
  resources:
    # static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources
    static-locations: classpath:/META-INF/resources,classpath:/META-INF/resources/dependency-ui
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    converters:
      preferred-json-mapper: fastjson
