---
spring:
  profiles: standalone
  datasource:
    url: jdbc:mysql://mysqlserver:3306/dummy?autoConnection=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    filters: log4j,mergeStat
    sql-script-encoding: UTF-8
    schema: classpath*:sql/*-schema.sql
    data: classpath*:sql/*-data.sql
    initialize: true
    
logging:
  level: debug
